### PR TITLE
Changing arguments for available packages

### LINKED ISSUE #303: build_home fails
It looks like the avilable.packages function does not like the ```repos``` argument, this function in build_home crashes.  Also, the cran_mirror returned, did not match the exact location of the package sources, returned by the function, so we also need to point it to the right path: 

```
pkgs <- utils::available.packages(
    type = "source",
    repos = list(CRAN = cran_mirror())

```
I found I fix and am about to submit a PR

### PR DESCRIPTION
**Pull request by edgararuiz**
Fixes #303 

Tested this fix with 3 different mirrors and they all worked: 

- cran <- as.list(getOption("source"))[["CRAN"]]
- cran <- "https://cran.usthb.dz/"
- cran <- "https://cran.cnr.berkeley.edu/"

Also tested it to build spark.rstudio.com and it  worked as well.

### CODE REVIEW

**Comment by hadley** [comment]
Would you mind adding a few unit tests?  That will require adding a `cran` parameter to `on_cran()`

**Comment by edgararuiz** [comment]
Sorry, I used the "cran <-" to simulate different default CRAN mirrors, I should have remove them in my comment.  This PR does not add or remove arguments to the function.

**Comment by hadley** [comment]
You should add a new argument, so you can write a unit test.

**Comment by edgararuiz** [comment]
Ok, it now has an option ```cran``` argument for unit testing.  Also added a test to test-build_home.R which passed.

File: R/build-home.R [hunk 1]
```diff
@@ -261,14 +261,15 @@ cran_mirror <- function() {
     cran
   }
 }
-on_cran <- function(pkg) {
+on_cran <- function(pkg, cran = NULL) {
```
Comment (hadley) [inline R/build-home.R]: Just set the default argument to `cran_mirror()`

BTW you shouldn't use `ifelse()` like this — it's exclusively for vectors. Instead you can use an inline if statement:

```R
cran <- if (is.null(cran)) cran_mirror() else cran
```

But this is such a common pattern most of my packages provide `%||%` so you can write:

```R
cran <- cran %||% cran_mirror()
```

But here I think it's fine to just set the default argument.

File: tests/testthat/test-build_home.R [hunk 2]
```diff
@@ -67,3 +67,30 @@ test_that("links to vignettes & figures tweaked", {
...
+test_that("package CRAN verification", {
+
+  #Package on CRAN, checking against default
+  expect_equal(on_cran("dplyr"), TRUE)
+  #Package on CRAN, checking against alternate mirror 1
+  expect_equal(on_cran("dplyr", "https://cran.stat.auckland.ac.nz"), TRUE)
+  #Package on CRAN, checking against alternate mirror 2
+  expect_equal(on_cran("dplyr", "https://cran.cnr.berkeley.edu"), TRUE)
+  #Package on CRAN, checking against alternate mirror 3
+  expect_equal(on_cran("dplyr", "https://cloud.r-project.org"), TRUE)
```
Comment (hadley) [inline tests/testthat/test-build_home.R]: I'd just use this mirror - the others are less reliable, and this tests that the complete code path works.

Comment (hadley) [inline tests/testthat/test-build_home.R]: You can also remove the comments.

**Comment by hadley** [comment]
Thanks!
