### PR TITLE
make rel_path() work on Windows

### LINKED ISSUE #307: invalid regular expression when building site in Windows 7
I was just getting started with this package and ran `pkgdown::build_site()` successfully once, but the next time I tried it I get an R code execution error below (I shortened the file paths with ***)

```
Error in FUN(X[[i]], ...) : 
  invalid regular expression '^C:\Users\A***\Documents\D***\t***\docs$'
In addition: Warning message:
In FUN(X[[i]], ...) : PCRE pattern compilation error
	'PCRE does not support \L, \l, \N{name}, \U, or \u'
	at 'Users\A***\Documents\D***\t***\docs$'
```

I'm using R 3.3.3 on Windows 7 and just installed roxygen2, and pkgdown from github today.  I'm guessing this is a backslash escaping things issue, so is there somewhere I should be adding a file.path() call?  

I get an identical error (with Windows filepaths as above since I cloned the repo with my package through git) when I try it on my mac (using osSierra, same versions of R and packages) but only when I try to run the build pkgdown addin from the menu or by keyboard shortcut. If i run pkgdown::build_site(), it works. 

Recreating my package from scratch in mac seems to have avoided this issue so it may be a Windows only thing. That is, building the site mac multiple times doesn't result in the invalid regular expression error

### LINKED ISSUE #409: rel_path doesn't work on Windows
I'm working on a package on Windows, and I ran into the absolute escape path issue #307. I isolate the problem to be an issue with `rel_path()`.

```r
pkgdown::rel_path("docs", ".")
#> [1] "C:\\Users\\mahr\\Desktop\\GitRepos\\littlelisteners\\docs"
```

<details> 

```
─ Session info ──────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.4.0 (2017-04-21)
 os       Windows 7 x64 SP 1          
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Chicago             
 date     2017-09-13                  

─ Packages ──────────────────────────────────────────────────────────────────────
 package     * version     date       source                                 
 clisymbols    1.2.0       2017-08-04 Github (gaborcsardi/clisymbols@e49b4f5)
 commonmark    1.4         2017-09-01 CRAN (R 3.4.1)                         
 devtools      1.13.3.9000 2017-09-13 Github (hadley/devtools@a0c8d73)       
 digest        0.6.12      2017-01-27 CRAN (R 3.3.2)                         
 magrittr      1.5         2014-11-22 CRAN (R 3.1.2)                         
 MASS          7.3-47      2017-02-26 CRAN (R 3.4.0)                         
 memoise       1.1.0       2017-04-21 CRAN (R 3.3.2)                         
 pkgbuild      0.0.0.9000  2017-09-13 Github (r-lib/pkgbuild@6574561)        
 pkgdown       0.1.0.9000  2017-09-13 Github (hadley/pkgdown@dd4635a)        
 pkgload       0.0.0.9000  2017-09-13 Github (r-lib/pkgload@6d4a7b6)         
 R6            2.2.2       2017-06-17 CRAN (R 3.4.0)                         
 Rcpp          0.12.12     2017-07-15 CRAN (R 3.4.1)                         
 rlang         0.1.2.9000  2017-09-13 Github (tidyverse/rlang@cf9de64)       
 roxygen2      6.0.1       2017-02-06 CRAN (R 3.3.2)                         
 sessioninfo   1.0.1       2017-09-13 Github (r-lib/sessioninfo@e813de4)     
 stringi       1.1.5       2017-04-07 CRAN (R 3.3.3)                         
 stringr       1.2.0       2017-02-18 CRAN (R 3.3.2)                         
 usethis       0.0.0.9000  2017-09-13 Github (r-lib/usethis@f2a6ac7)         
 withr         2.0.0       2017-09-13 Github (jimhester/withr@5e6cc35)       
 xml2          1.1.1       2017-01-24 CRAN (R 3.3.2)                         
 yaml          2.1.14      2016-11-12 CRAN (R 3.3.2)   
```

</details>

### PR DESCRIPTION
**Pull request by tjmahr**
Closes #409.

Also related to #307.

`normalizePath()` documentation says:

  > On Windows it converts relative paths to absolute paths, converts short names for path elements to long names and ensures the separator is that specified by winslash. It will match paths case-insensitively and return the canonical case. UTF-8-encoded paths not valid in the current locale can be used.

So that's why `rel_path()` didn't work on Windows.

To fix this, I first normalize the path directory and the current directory. The difference between the two strings is the relative path, so I use string-replacement to extract it out. 

This function below illustrates what happens inside the function on Windows.

```r
windows_rel_path_demo <- function(path, base) {
  if (is_absolute_path(path)) {
    path
  } else {
    if (base != ".") {
      path <- file.path(base, path)
    }
    # normalizePath() on Windows expands to absolute paths,
    # so strip normalized base from normalized path
    if (Sys.info()["sysname"] == "Windows") {
      parent_full <- normalizePath(".", mustWork = FALSE, winslash = "/")
      path_full <- normalizePath(path, mustWork = FALSE, winslash = "/")
      diff <- gsub(paste0(parent_full, "/"), "", path_full)
      list(
        base = base,
        path = path,
        parent_full = parent_full,
        path_full = path_full,
        diff = diff
      )
    } else {
      list()
    }
  }
}

is_absolute_path <- function(path) {
  grepl("^(/|[A-Za-z]:|\\\\|~)", path)
}

str(windows_rel_path_demo("docs", "."))
#> List of 5
#>  $ base       : chr "."
#>  $ path       : chr "docs"
#>  $ parent_full: chr "C:/Users/mahr/Desktop/GitRepos/pkgdown"
#>  $ path_full  : chr "C:/Users/mahr/Desktop/GitRepos/pkgdown/docs"
#>  $ diff       : chr "docs"
str(windows_rel_path_demo("site", "inst"))
#> List of 5
#>  $ base       : chr "inst"
#>  $ path       : chr "inst/site"
#>  $ parent_full: chr "C:/Users/mahr/Desktop/GitRepos/pkgdown"
#>  $ path_full  : chr "C:/Users/mahr/Desktop/GitRepos/pkgdown/inst/site"
#>  $ diff       : chr "inst/site"
```

### CODE REVIEW

File: R/util.r [hunk 1]
```diff
@@ -164,7 +164,15 @@ rel_path <- function(path, base = ".") {
     if (base != ".") {
       path <- file.path(base, path)
     }
-    normalizePath(path, mustWork = FALSE)
+    # normalizePath() on Windows expands to absolute paths,
```
Comment (hadley) [inline R/util.r]: I wonder if we should extract out:

```R
on_windows <- function() {
  Sys.info()["sysname"] == "Windows"
}
```

And then change the signature of `rel_path()` to `rel_path <- function(path, base = ".", windows = is_windows())`. That would make testing easier.

**Comment by tjmahr** [comment]
I factored out an `on_windows()` function, made it an argument, and added more tests.

The function will only work on Windows if the `windows` argument is true, so the non-Windows test has to be skipped on Windows.

```
test_that("rel_path() returns a relative path (#409)", {
  skip_on_os("windows")
  expect_equal(rel_path("a/b", "here", windows = FALSE), "here/a/b")
  expect_equal(rel_path("a/b", ".", windows = FALSE), "a/b")
})
```

The naive work-around for Windows should work on any OS---okay I tried Windows and Linux. As a result, this test doesn't check the OS and always runs.

```
test_that("rel_path() for Windows compares strings to find path (#409)", {
  expect_equal(rel_path("a/b", "here", windows = TRUE), "here/a/b")
  expect_equal(rel_path("a/b", ".", windows = TRUE), "a/b")
})
```

File: R/util.r [hunk 2]
```diff
@@ -153,21 +153,35 @@ find_first_existing <- function(path, ...) {
...
+    # so strip normalized base from normalized path
+    if (windows) {
+      parent_full <- normalizePath(".", mustWork = FALSE, winslash = "/")
+      path_full <- normalizePath(path, mustWork = FALSE, winslash = "/")
+      gsub(paste0(parent_full, "/"), "", path_full)
```
Comment (hadley) [inline R/util.r]: This should probably be `fixed = TRUE` for safety

Comment (tjmahr) [reply R/util.r]: done!

**Comment by hadley** [comment]
Thanks!
